name: "Rampart Policy Check"
description: "Lint Rampart policies and benchmark coverage against known attack patterns"
branding:
  icon: "shield"
  color: "red"
inputs:
  policy:
    description: "Path to policy file or directory"
    required: false
    default: ".rampart/policies/"
  min-coverage:
    description: "Fail if coverage drops below this percentage (0 = just report)"
    required: false
    default: "0"
  severity:
    description: "Minimum severity: critical, high, or medium"
    required: false
    default: "medium"
  version:
    description: "Rampart version to install (default: latest)"
    required: false
    default: "latest"
  strict:
    description: "Strict mode — require_approval does not count as covered"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Install Rampart (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = "latest" ]; then
          VERSION=$(curl -fsSL https://api.github.com/repos/peg/rampart/releases/latest | grep '"tag_name"' | cut -d'"' -f4)
        fi
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        if [ "$ARCH" = "x86_64" ]; then ARCH="amd64"; fi
        if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then ARCH="arm64"; fi
        URL="https://github.com/peg/rampart/releases/download/${VERSION}/rampart_${VERSION#v}_${OS}_${ARCH}.tar.gz"
        echo "Installing rampart ${VERSION} from ${URL}"
        curl -fsSL "$URL" -o /tmp/rampart.tar.gz
        tar -xz -C /tmp -f /tmp/rampart.tar.gz rampart
        sudo mv /tmp/rampart /usr/local/bin/rampart
        rampart version

    - name: Install Rampart (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $Version = "${{ inputs.version }}"
        if ($Version -eq "latest") {
          $Release = Invoke-RestMethod "https://api.github.com/repos/peg/rampart/releases/latest"
          $Version = $Release.tag_name
        }
        $VersionNum = $Version.TrimStart("v")
        $Url = "https://github.com/peg/rampart/releases/download/${Version}/rampart_${VersionNum}_windows_amd64.zip"
        Write-Host "Installing rampart ${Version}"
        Invoke-WebRequest -Uri $Url -OutFile "$env:TEMP\rampart.zip"
        Expand-Archive "$env:TEMP\rampart.zip" -DestinationPath "$env:TEMP\rampart"
        $InstallDir = "$env:USERPROFILE\.rampart\bin"
        New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
        Copy-Item "$env:TEMP\rampart\rampart.exe" "$InstallDir\rampart.exe"
        echo "$InstallDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        & "$InstallDir\rampart.exe" version

    - name: Lint policy
      shell: bash
      run: |
        echo "::group::Rampart Policy Lint"
        rampart policy lint "${{ inputs.policy }}"
        EXIT=$?
        echo "::endgroup::"
        exit $EXIT

    - name: Benchmark coverage
      shell: bash
      run: |
        STRICT_FLAG=""
        if [ "${{ inputs.strict }}" = "true" ]; then
          STRICT_FLAG="--strict"
        fi
        MIN_COV_FLAG=""
        if [ "${{ inputs.min-coverage }}" != "0" ]; then
          MIN_COV_FLAG="--min-coverage ${{ inputs.min-coverage }}"
        fi
        echo "::group::Rampart Bench"
        rampart bench --policy "${{ inputs.policy }}" --severity "${{ inputs.severity }}" $STRICT_FLAG $MIN_COV_FLAG
        EXIT=$?
        echo "::endgroup::"
        exit $EXIT
